#ifndef _SRC_CODE_OSDLCONFIG_FOR_WINDOWS_H
#define _SRC_CODE_OSDLCONFIG_FOR_WINDOWS_H 1
 
/* src/code/OSDLConfig.h. Generated automatically at end of configure. */
/* src/code/OSDLTemporaryConfig.h.  Generated by configure.  */
/* src/code/OSDLTemporaryConfig.h.in.  Generated from configure.ac by autoheader.  */

/* Unless specified otherwise, all those preprocessor symbols should */
/* be tested with #ifdef (not #if) */


/* Windows specific section */

/* Define the maximum number of sockets supported */
/* see http://msdn.microsoft.com/library/default.asp?url=/library/en-us/winsock/winsock/porting_socket_applications_to_winsock.asp */
#define FD_SETSIZE 128

/* For faster Builds and Smaller Header Files */
/* (beware to compile errors that it might generate ) */
#define VC_EXTRALEAN
#define WIN32_LEAN_AND_MEAN



/* General section */

/* 
/* Define to 1 if the target platform is FreeBSD */
#ifndef OSDL_ARCH_FREEBSD 
#define OSDL_ARCH_FREEBSD  0 
#endif

/* Define to 1 if the target platform is GNU/Linux */
#ifndef OSDL_ARCH_LINUX 
#define OSDL_ARCH_LINUX  0
#endif

/* Define to 1 if the target platform is NetBSD */
#ifndef OSDL_ARCH_NETBSD 
#define OSDL_ARCH_NETBSD  0 
#endif

/* Define to 1 if the target platform is OpenBSD */
#ifndef OSDL_ARCH_OPENBSD 
#define OSDL_ARCH_OPENBSD  0 
#endif

/* Define to 1 if the target platform is a BSD one */
#if OSDL_ARCH_FREEBSD ||  OSDL_ARCH_NETBSD || OSDL_ARCH_OPENBSD
#define OSDL_ARCH_BSD 1
#endif

// By default, not BSD :
#ifndef OSDL_ARCH_BSD 
#define OSDL_ARCH_BSD  0 
#endif


/* Define to 1 if the target platform is a UNIX one */
#if OSDL_ARCH_BSD || OSDL_ARCH_LINUX
#define OSDL_ARCH_UNIX 1
#endif

// By default, not UNIX :
#ifndef OSDL_ARCH_UNIX 
#define OSDL_ARCH_UNIX  0 
#endif

/* Define to 1 if the target platform is a Windows one */
#ifndef OSDL_ARCH_WINDOWS 
#define OSDL_ARCH_WINDOWS  1 
#endif

// By default, not UNIX :
#ifndef OSDL_ARCH_UNIX 
#define OSDL_ARCH_UNIX  0 
#endif

/* Define to 1 if the `closedir' function returns void instead of `int'. */
/* #undef OSDL_CLOSEDIR_VOID */


/* Define to 1 if you have the `abs' function. */
#ifndef OSDL_USES_ABS 
#define OSDL_USES_ABS  1 
#endif


/* Version number of package */
#ifndef OSDL_VERSION 
#define OSDL_VERSION  "0.3" 
#endif


/* once: _SRC_CODE_OSDLCONFIG_FOR_WINDOWS_H */
#endif
