#!/bin/sh


USAGE="Usage: "`basename $0`": cleans the OSDL test repository by removing all files generated by the tests. Useful while preparing a release."

FIND=`which find 2>/dev/null`
#echo "FIND = $FIND"

RM="/bin/rm"


echo "    Cleaning files generated by tests"

# Directories:
$FIND . -name 'testOSDL*-logs' -exec $RM -rf '{}' ';' 2>/dev/null

# Files:
$FIND . \( -name 'testOSDL*.png' -o -name 'testOSDL*.bmp' -o -name 'testOSDL*.pal' -o -name 'testOSDL*.rgb' -o -name 'testOSDL*.log' -o -name 'testOSDL*.xml' -o -name testsOutcome.txt \) -exec $RM -f '{}' ';' 2>/dev/null
								 
#echo "    Cleaning of files generated by tests done."

