
# Added so that GraphicalCharter-docutils.html can be generated here.


PROJECT_CSS = css/OSDL-docutils.css


include ../../../../../../../ceylan/Ceylan/trunk/src/doc/GNUmakerules-docutils.inc


doc: GraphicalCharter-docutils.html
